barostatconstratio: true
boxsize: input.xsc
coordinates: input.coor
cutoff: 9
parameters: parameters
pme: true
restart: true
run: 5us
structure: structure.psf
switchdistance: 7.5
switching: true
thermostat: true
thermostatdamping: 0.1
thermostattemperature: 310
timestep: 4
trajectoryfile: output.xtc
trajectoryperiod: 50000
velocities: 310
